export interface QnaItem {
  question: string;
  answer: string;
}

// "Najčastejšie otázky" — exact copy from https://volnekridla.sk/volne-kridla (#faq) — do not paraphrase
export const qna: QnaItem[] = [
  {
    question: "Je voľné lietanie bezpečné? Aké sú možné riziká?",
    answer:
      "Lietanie vonku s papagájmi prináša riziká, ktoré treba mať na pamäti:\n\nPočasie: náhle zmeny a silný vietor môžu byť pre nedostatočne trénovaného papagája nebezpečné.\n\nÚrazy: Pri lietaní sa môže zraniť napríklad pri náraze do skla, elektrických vedení alebo iných prekážok avšak tento druh rizika je najmenej pravdepodobný, aj vďaka správnemu výberu miesta na tréning voľného lietania.\n\nStrety s inými zvieratami: dravce alebo pohyb iných vtákov predstavujú riziko, najmä pre menších papagájov. Ary vo všeobecnosti vzbudzujú rešpekt jednak svojou veľkosťou, sfarbením ale aj svojim hlasným prejavom.\n\nÚtek/únikový reflex: Rovnako ako všetci vtáci majú aj papagáje inštinktívny únikový reflex, ktorý ich chráni aby sa vo voľnej prírode nestali korisťou. Pretože sa jedna o reflexný pohyb, nemôže ho papagáj príliš ovplyvňovať. Únikový reflex spôsobuje, že sa papagáj okamžite vznesie do vzduchu akonáhle sa cíti ohrozený iným tvorom alebo pohybom a čo najrýchlejšie letí preč od zdroja nebezpečia až tam, kde sa cíti bezpečne.\n\nTieto riziká sami nezmiznú no správnym a postupným tréningom ich dokážeme výrazne znížiť. V rámci letového kurzu VOĽNÉ KRÍDLA vysvetľujem postupy aj riziká, učím recall, bezpečný výber miest a časov letu. Preto je tréning správna voľba — dá vám istotu, naučí papagája bezpečnému správaniu a výrazne zníži riziká pri voľnom lete. Chcete začať bezpečne? Kontaktujte ma a prejdeme to krok za krokom.",
  },
  {
    question: "Dá sa trénovať aj papagáj, ktorý nie je zvyknutý na traky?",
    answer:
      "Z môjho pohľadu je trénovanie s pomocou trakov najbezpečnejšie. Avšak áno, dá sa trénovať aj bez trakov no tento tréning je o niečo náročnejší a začína ešte v čase dokrmovania papagája čiže je založený na silnom pute medzi vami a papagájom.",
  },
  {
    question:
      "V akom veku je najlepšie začať s tréningom? Dá sa naučiť na voľný let aj starši papagáj?",
    answer:
      "Ak začínate s papagájom vo veku v akom by prirodzene lietal vo voľnej prírode, je to oveľa jednoduchšie (papagáj prirodzene chce lietať a nepotrebuje k tomu veľké povzbudzovanie).\n\nPri starších papagájoch najčastejšie strávime väčšinu času odstraňovaním súčasných zlozvykov a tympádom to môže trvať o niečo dlhšie ako u mláďat.\n\nAvšak dobrá správa je, že na veku vášho papagája až tak nezáleží, pretože všetky papagáje sú schopné učiť sa v akomkoľvek veku avšak podmienka je, že si musí nechať nasadiť traky na lietanie, čo u starších papagájoch môže byť problém.",
  },
];

// "Tipy, triky a zaujímavosti" — exact copy from https://volnekridla.sk/volne-kridla (#tips) — do not paraphrase
export const tips: QnaItem[] = [
  {
    question: "Kliker pri práci s papagájmi 🦜🚀",
    answer:
      "Používanie klikera pri výcviku papagájov má mnoho výhod, pretože umožňuje efektívnejšiu a presnejšiu komunikáciu medzi tebou a tvojím opereným zverencom. Tu sú hlavné dôvody, prečo ho používať:\n\n1. Presnosť a rýchlosť odmeny\n\nKliker umožňuje označiť presne ten moment, keď papagáj vykoná správne správanie. To je dôležité, pretože ak by si použil len odmenu (napr. pamlsky), môže dôjsť k oneskoreniu a papagáj nemusí pochopiť, za čo bol odmenený.\n\n2. Jasná komunikácia\n\nZvuk klilera je vždy rovnaký a jednoznačný, na rozdiel od slovného pochválenia, ktoré môže mať rôzne tóny alebo emócie. Papagáj si rýchlo spojí kliknutie s odmenou a ľahšie pochopí, čo od neho chceš.\n\n3. Zvyšuje motiváciu a rýchlosť učenia\n\nKeď papagáj pochopí princíp klikera, začne sa učiť nové triky rýchlejšie. Vie, že správne správanie vedie ku kliknutiu a následnej odmene, takže sa viac snaží.\n\n4. Obmedzenie nežiaducich zvykov\n\nKeď používaš kliker, môžeš posilňovať iba žiaduce správanie a ignorovať alebo presmerovať nežiaduce správanie. Papagáj si tak zvykne robiť to, čo je správne, aby získal odmenu.\n\n5. Funguje na všetkých papagájov\n\nNezáleží na tom, či trénuješ malú andulku alebo veľkú aru – klikerový tréning je univerzálny a funguje na všetky druhy papagájov.\n\nTip: Začni s jednoduchými úlohami, napríklad s privolaním na ruku alebo dotykom zobáka na cieľový predmet. Akonáhle papagáj pochopí princíp klikera, môžeš postupne prechádzať k zložitejším trikom a voľnému letu.",
  },
  {
    question: "Šťastný papagáj aj bez voľného lietania? Určite ÁNO 🦜🌟",
    answer:
      "Voľné lietanie je skvelé, ale nie každý papagáj musí lietať vonku, aby bol šťastný. Aj v bezpečí domova môže mať plnohodnotný život, ak mu vytvoríme správne podmienky.\n\n✅ Priestranná klietka a výbeh – Papagáj potrebuje dostatok miesta na pohyb, lezenie a naťahovanie krídel. Ideálne je kombinovať klietku s hracou zónou mimo nej.\n\n✅ Stimulujúce prostredie – Hračky, vetvy, laná, hlavolamy a stále nové podnety pomáhajú udržať papagája mentálne aktívneho a šťastného.\n\n✅ Zdravá strava – Pestrá a vyvážená strava je základ zdravého života. Ovocie, zelenina, semienka, orechy a kvalitné granule zabezpečia všetko potrebné.\n\n✅ Sociálny kontakt – Papagáje sú spoločenské tvory, ktoré potrebujú interakciu. Každodenná pozornosť, rozhovory a tréning posilňujú vzťah medzi vtákom a majiteľom.\n\n✅ Možnosť lietať v interiéri – Ak je to bezpečné, umožnite papagájovi pravidelné prelety po miestnosti. Pomáha to udržať ho v dobrej fyzickej kondícii.\n\nPapagáj, ktorý má dostatok pozornosti, podnetov a starostlivosti, môže byť šťastný a spokojný aj bez voľného lietania. Dôležité je vytvoriť mu prostredie, v ktorom sa cíti dobre a bezpečne ❤️",
  },
  {
    question: "Tréning recallu (privolania) 🦜🍀",
    answer:
      "je dôležitý nie len pre voľnoletcov ale aj pre nevoľnoletcov\n\nAko trénovať recall krok za krokom:\n\n1. Vytvorenie pozitívneho vzťahu s menom a povelom\n\n🔹 Začni v pokojnom prostredí, kde sa papagáj cíti bezpečne.\n\n🔹 Používaj rovnaké slovo pri privolaní (napr. “Poď sem!”, “Ku mne!” alebo len meno).\n\n🔹 Keď papagáj príde bližšie, okamžite ho odmeň (oblúbená pochúťka, pohladenie alebo pochvala).\n\n2. Krátke vzdialenosti – tréning na ruke alebo v izbe\n\n🔹 Začni na krátke vzdialenosti – pár centimetrov medzi rukami.\n\n🔹 Volaj ho, ukáž mu odmenu a odmeň ho, keď príde.\n\n🔹 Postupne zväčšuj vzdialenosť – najskôr v rámci miestnosti.\n\n3. Tréning v dlhších vzdialenostiach (vo vnútri aj vonku)\n\n🔹 Keď ovláda recall na krátke vzdialenosti, začni ho trénovať cez celú miestnosť.\n\n🔹 Ak si istý, že rozumie povelu, môžeš skúsiť vonku, ale v bezpečnom priestore (voliéra, alebo za použití trakov na lietanie)\n\n🔹 Použi dlhšiu trasu a viaceré zastávky – zavolaj ho z bodu A do bodu B\n\n4. Recall vonku – bezpečné prostredie\n\n🔹 Najprv v kontrolovaných podmienkach – na dvoroch, v sieťovaných voliérách, s postrojom.\n\n🔹 Trénuj v bezpečnej oblasti bez rušivých vplyvov, kde sa cíti komfortne.\n\n🔹 Zlepšuj jeho reakčný čas – odmeň ho len za rýchlu odozvu.\n\n5. Použitie odmien a variabilného posilňovania\n\n🔹 Nie vždy daj jedlo – neskôr stačí len pochvala alebo hra.\n\n🔹 Používaj variabilné odmeny – niekedy väčšia, niekedy menšia odmena, aby zostal motivovaný.\n\n6. Tréning s rušivými vplyvmi\n\n🔹 Po čase vyskúšaj recall v rušnejšom prostredí (viac ľudí, zvuky).\n\n🔹 Trénuj, aj keď je vystresovaný – aby si bol istý, že príde aj v nečakaných situáciách.\n\n➡️ Dôležité tipy:\n\n✅ Buď trpezlivý – niektorým papagájom to trvá dlhšie.\n\n✅ Nikdy ho netrestaj, ak nepriletí – recall musí byť vždy pozitívny zážitok.",
  },
  {
    question: "Ako správne ponúknuť ovocie🦜 🍇",
    answer:
      "Každý chovateľ sa snaží ponúknuť čo najširšiu škálu ovocia, často pripravuje ovocné šaláty, v ktorých sú rôzne druhy ovocia nakrájané na malé kúsky a zmiešané dohromady. Táto farebná rozmanitosť je atraktívna pre ľudí, a preto sa predpokladá, že sa páči aj vtákom. To však nie je pravda!\n\nKaždý papagáj má svoje obľúbené ovocie a bude sa ho snažiť vybrať zo zmesi, pričom zvyšok nechá v miske alebo ho rozhádže po zemi.\n\nStačilo by sa pozrieť na prírodu, aby sme pochopili, ako papagáje a iné druhy papagájovitých vtákov kombinujú svoju stravu vo voľnej prírode.\n\nAko sa papagáje kŕmia v prírode?\n\nZväčša celé kŕdle pristávajú na jednom ovocnom strome a živia sa ním, kým sa všetci nenajedia, potom odletia. Konzumujú iba jeden druh ovocia, pričom ho jedia niekoľko dní, kým nie je úplne spotrebované. Potom musia hľadať nový zdroj potravy.\n\nPodľa ročného obdobia jedia to ovocie, ktoré je práve dostupné, a pokračujú v jeho konzumácii, kým sa zásoby nevyčerpajú.\n\nAko využiť tento prirodzený spôsob kŕmenia v zajatí?\n\nJe dokázané, že papagáje uprednostňujú jedno konkrétne ovocie, aj keď im ponúkneme rôzne druhy v jednom ovocnom šaláte. Vyberú si obľúbený druh a ostatné ignorujú alebo rozhádžu.\n\nPreto sa odporúča podávať denne len jeden druh ovocia.\n\n• Každý deň iné ovocie, aby sa počas týždňa dosiahla pestrosť v strave.\n\n• Týmto spôsobom sa papagáj môže naučiť akceptovať a obľúbiť si nové druhy ovocia.\n\n• Rovnaký princíp platí aj pre zeleninu.\n\nZáver\n\nSprávne kŕmenie papagájov by malo napodobňovať ich prirodzené správanie v prírode. Podávanie potravy v samostatných miskách a ponúkanie iba jedného druhu ovocia denne pomáha zabezpečiť vyváženú stravu a predchádza plytvaniu potravou.",
  },
  {
    question: "Interaktívne kŕmenie ako motivácia🦜👌",
    answer:
      "Papagáje potrebujú nielen fyzickú aktivitu, ale aj mentálnu stimuláciu! 🧠✨ Využi jedlo na zábavné učenie a posilňovanie ich prirodzených schopností:\n\n🔹 Hlavolamy na jedlo – nech si maškrtu vydobyjú z hračky\n\n🔹 Hľadanie jedla – schovaj odmenu a sleduj, ako ju objavia\n\n🔹 Tréning trikov – točenie, podanie nôžky alebo iné šikovnosti výmenou za obľúbenú pochúťku",
  },
  {
    question: "Papagáje a konzumácia hliny: Prečo to robia? 🦜🤔",
    answer:
      "Papagáje sú známe svojím zvykom konzumovať hlinu, čo je správanie pozorované u viacerých druhov, najmä v Južnej Amerike. Tento jav, nazývaný geofágia, zaujal mnoho výskumníkov a viedol k viacerým teóriám o jeho príčinách.\n\nNeutralizácia rastlinných toxínov\n\nJedno z najuznávanejších vysvetlení je, že hlina pomáha papagájom neutralizovať toxíny nachádzajúce sa v niektorých rastlinných potravinách, ktoré konzumujú. Mnohé rastliny produkujú toxické látky ako obranný mechanizmus proti bylinožravcom. Konzumáciou hliny môžu papagáje tieto toxíny viazať, čím sa znižuje ich vstrebávanie a chráni sa tak ich organizmus.\n\nDoplnenie esenciálnych minerálov\n\nĎalšia teória naznačuje, že hlina poskytuje dôležité minerály, ako sú sodík a vápnik, ktoré môžu v prirodzenej strave papagájov chýbať. Clay licks (steny z hliny) sú často bohaté na tieto minerály a ich konzumácia môže pomôcť pokryť nutričné potreby vtákov.\n\nZlepšenie trávenia\n\nHlina môže tiež uľahčiť trávenie tým, že sa viaže na ťažko stráviteľné látky, čím zlepšuje účinnosť vstrebávania živín. Okrem toho môže pôsobiť ako prírodné antacidum, ktoré zmierňuje prípadné tráviace ťažkosti.\n\nZníženie črevných parazitov\n\nNiektoré štúdie naznačujú, že konzumácia hliny môže pomôcť znížiť prítomnosť črevných parazitov, čím sa zlepšuje celkové zdravie papagájov.\n\nPozorovania v zajatí\n\nV zajatí bolo zistené, že poskytovanie hliny papagájom môže mať podobné výhody – pomáha pri vyvážení stravy a poskytuje im mentálne obohatenie. Je však dôležité zabezpečiť, aby bola hlina bezpečná na konzumáciu a neobsahovala škodlivé látky.\n\nZáver\n\nGeofágia u papagájov je multifunkčné správanie, ktoré prispieva k ich zdraviu prostredníctvom neutralizácie toxínov, doplnenia minerálov, zlepšenia trávenia a redukcie parazitov.",
  },
  {
    question: "Prečo papagáje toľko plytvajú jedlom? 👇😉",
    answer:
      "V zajatí patrí medzi najviac diskutované témy otázka: “Prečo moje papagáje plytvajú jedlom?” Prečo hádžu a rozhadzujú potravu okolo seba? Často vyhadzujú viac, než zjedia – niekedy až viac než 80 %jedla.\n\nToto správanie však nie je obmedzené len na papagáje v zajatí, ale je v nich geneticky zakódované. Takéto správanie sa pozorovalo u všetkých druhov papagájov.\n\nVýskumné údaje pokrývajúce 103 druhov v 17 krajinách, čo predstavuje asi 30 % všetkých papagájích druhov vo voľnej prírode, ukázali, že plytvanie jedlom je bežné. Či už ide o aru arakangu zo Južnej Ameriky, kakadu žltolícího z Austrálie, alebo žaka sivého z Afriky – všetky tieto druhy vyhadzovali až 80 % potravy, ktorú si vzali.\n\nPodľa niektorých ornitológov a vedcov je toto správanie zámerné.\n\nDáta ukazujú, že papagáje častejšie púšťali nezrelé ovocie ako to zrelé. Tiež sa ukázalo, že hádzanie potravy sa výrazne znížilo počas obdobia hniezdenia, najmä keď mali mláďatá.\n\nToto správanie môže podporovať ekosystémy. Bolo pozorované, že až 86 druhov zvierat – od mravcov až po dobytok – konzumujú potravu, ktorú papagáje zhodili. Tieto zvieratá následne šíria semená, čím prispievajú k udržiavaniu rovnováhy v prírode.\n\nPrečo to teda papagáje robia?\n\nZatiaľ neexistuje jednoznačná odpoveď. Ale je potvrdené, že to robia zámerne. Keďže sa to deje naprieč rôznymi regiónmi a druhmi, predpokladá sa, že ide o inštinktívne správanie. Možno nimi niečo ženie k tomu, aby jedlo rozhadzovali, čím zabezpečia, že ďalšia úroda prinesie väčšie a sladšie plody, a šírenie semien im zaistí viac potravy v budúcnosti.\n\nIch prirodzené prostredie je podporované ich zvykom rozhadzovať jedlo a pomáhať pri šírení semien. Dá sa povedať, že papagáje významne prispievajú k ochrane svojho životného prostredia a zohrávajú kľúčovú úlohu pri ekologickej rovnováhe.\n\nPrečo papagáje toľko plytvajú jedlom?\n\nČasto vyhadzujú viac, než zjedia – niekedy až viac než 80 % jedla.\n\nToto správanie však nie je obmedzené len na papagáje v zajatí, ale je v nich geneticky zakódované\n\nPapagáje pomáhajú prírode tým, že rozhadzujú jedlo a šíria semienka. Aj vďaka tomu chránia svoje prostredie a pomáhajú udržať rovnováhu v prírode.",
  },
  {
    question: "Ako motivovať papagája jedlom? 🫐",
    answer:
      "1. Vyber správnu odmenu 🫛🥜\n\n• Každý papagáj má iné preferencie. Vyskúšaj rôzne maškrty a sleduj, na ktoré reaguje najviac\n\n2.Používaj odmeny len počas tréningu\n\n• Aby odmena bola motivujúca, nemala by byť bežnou súčasťou denného jedálnička.\n\n• Ak papagáj dostáva obľúbené jedlo kedykoľvek, nebude mať motiváciu pracovať zaň.\n\n• Môžeš mierne obmedziť kŕmenie pred tréningom (nie však hladovať), aby bol viac motivovaný.\n\n3. Okamžitá odmena za správne správanie\n\n• Daj odmenu ihneď, keď papagáj vykoná požadovanú akciu. Čím rýchlejšie príde odmena, tým lepšie si spojí akciu s pozitívnym výsledkom.\n\n• Môžeš použiť aj kliker tréning – klikneš klikrom a hneď na to dáš odmenu, čím si papagáj lepšie uvedomí, za čo ju dostal.\n\nVariabilita a postupné znižovanie odmien\n\n• Ak papagáj už dobre ovláda daný trik, postupne zníž frekvenciu odmien.\n\n• Môžeš ho odmeňovať niekedy jedlom, inokedy pochvalou alebo pohladením.\n\n• Používaj rôzne druhy odmien, aby ho tréning neomrzel.\n\nNepoužívaj jedlo ako nátlak\n\n• Odmena by mala byť motiváciou, nie manipuláciou. Ak papagáj nie je ochotný spolupracovať, netlač naňho, radšej vyskúšaj iný čas alebo inú stratégiu.\n\n• Ak je papagáj prejedaný alebo vystresovaný, ani obľúbené jedlo ho nemusí motivovať.",
  },
  {
    question: "Čomu sa vyhnúť v domácnosti s papagájom? 🚫",
    answer:
      "Papagáje sú veľmi citlivé na rôzne látky a predmety, ktoré sú pre ľudí bežné, no pre nich môžu byť nebezpečné až smrteľné. Tu je prehľad vecí, ktoré by sa nemali používať v domácnosti s papagájom:\n\nNebezpečné látky a produkty:\n\n1. Teflón a iné nepriľnavé povrchy (PTFE/PFOA)\n\n• Pri prehriatí (už nad 240 °C) uvoľňujú toxické výpary, ktoré môžu spôsobiť u papagája náhlu smrť.\n\n• Pozor na panvice, hriankovače, žehličky, rúry, ohrievače.\n\n2. Aerosóly a spreje\n\n• Parfémy, osviežovače vzduchu, čističe, laky na vlasy – všetky môžu spôsobiť problémy s dýchaním alebo otravu.\n\n3. Fajčenie a nikotín\n\n• Cigarety, elektronické cigarety aj pasívne fajčenie sú pre papagája extrémne toxické.\n\n4. Sviečky a vonné tyčinky\n\n• Parfumované alebo parafínové sviečky môžu uvoľňovať výpary škodlivé pre papagájov.\n\n5. Niektoré rastliny\n\n• Jedovaté pre papagáje: napr. monstera, ľalie, azalka, oleander, ficus, tulipány, svokrin jazyk, dracena.\n\n6. Čistiace prostriedky a bielidlá\n\n• Silné chemikálie, amoniak, bielidlo a dezinfekčné prostriedky sú toxické aj vo forme výparov.\n\n7. Esenciálne oleje\n\n• Mnohé oleje (napr. tea tree, eukalyptus, citrusy) sú pre papagáje toxické aj len vdýchnutím.",
  },
  {
    question: "Medzidruhové vzťahy = ľudská ilúzia, =riziko pre papagája 💬🦜",
    answer:
      "Nechajte papagája žiť s ostatnými papagájmi rovnakého druhu: reč tela je druhovo špecifická.\nPredstava, že medzi rôznymi druhmi papagájov možno vytvoriť harmonické “priateľstvá” alebo pevné partnerské väzby, je vo väčšine prípadov len ľudskou ilúziou.\n\nV prírode sa odlišné druhy papagájov stretávajú len zriedkavo a ich vzájomná interakcia je obmedzená, najmä počas hniezdneho obdobia alebo pri súťažení o potravu. V zajatí sa však často nútene dostávajú do tesného kontaktu, čo pre nich môže predstavovať riziko – od vzniku konfliktov a stresu až po fyzické zranenia. Každý druh má svoje špecifické správanie, spôsob komunikácie a “osobný priestor”, a to, čo my vnímame ako priateľskú interakciu, môže byť v skutočnosti varovný signál alebo začiatok agresie. Preto je dôležité pozerať sa na vzťahy medzi papagájmi z ich pohľadu, nie z nášho, a zabezpečiť im podmienky, v ktorých sa budú cítiť bezpečne a prirodzene.\n\nPretože rešpektovať túto skutočnosť znamená dať mu to, čo naozaj potrebuje, nie to, čo si myslíme, že ho robí šťastným.",
  },
  {
    question: "Kŕmenie peletami – áno či nie?🤔",
    answer:
      "Kŕmenie domácich papagájov je témou veľkého záujmu medzi nadšencami aj chovateľmi. V posledných desaťročiach vyvolalo zavedenie peliet ako súčasti stravy diskusie o ich prínosoch a možných obmedzeniach.\nVýhody peliet v kŕmení papagájov\n\n• Vyvážená strava: Pelety sú formulované tak, aby poskytovali všetky základné živiny potrebné pre vyváženú diétu, čím sa znižuje riziko bežných nutričných nedostatkov pri strave založenej výhradne na semenách.\n\nNevýhody a kritika používania peliet\n\n• Neprirodzená potrava: Niektorí tvrdia, že pelety predstavujú “cudzí” druh potravy pre papagáje, vzdialený ich prirodzenej strave. To vyvoláva otázky o ich prijateľnosti a psychickej pohode vtákov kŕmených výhradne peletami.\n\nVývoj výživových odporúčaní\n\nSpočiatku boli pelety propagované ako úplná náhrada tradičnej stravy papagájov. Postupom času sa však ukázalo, že strava výlučne založená na peletách nemusí úplne pokrývať nutričné no najmä behaviorálne potreby všetkých druhov. V súčasnosti mnohí odborníci odporúčajú, aby pelety tvorili približne 30 % celkovej stravy, doplnené čerstvým ovocím, zeleninou a inými prírodnými potravinami.\n\nA ak pelety, tak určite siahnúť iba po kvalitných peletách bez umelých farbív, aróm a konzervantov.",
  },
];
